# Next Word Prediction Model

## Problem Statement

   We often seen while browsing internet, when we are searching for something browser will automatically recommend set of words related to the topic before we type.preloaded data is also stored in the keyboard function of our smartphones to predict the next word correctly.
   
   This project is useful in various applications, including autocomplete suggestions in search engines, text messaging, and improving the efficiency of virtual assistants and chatbots by making their responses more contextually relevant and coherent.
   
   I have used Tensorflow and Keras library in Python for next word prediction model.



## GitHub Link -

https://github.com/PrathameshKhochare/-LGMVIP--DataScience

# ***Let's Begin !***

#### Import Libraries

In [3]:
## Data Maipulation Libraries
!pip install tensorflow
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam
import pickle
import numpy as np
import pandas as pd
import os

# Library of warnings would assist in ignoring warnings issued
import warnings;warnings.filterwarnings('ignore')
import warnings;warnings.simplefilter('ignore')
 
# Importing module to see execution time in mili seconds
!pip install ipython-autotime
%load_ext autotime

     -------------------------------------- 276.5/276.5 MB 1.9 MB/s eta 0:00:00
     -------------------------------------- 430.4/430.4 kB 3.4 MB/s eta 0:00:00
     ------------------------------------ 440.8/440.8 kB 492.1 kB/s eta 0:00:00
     ---------------------------------------- 24.4/24.4 MB 2.8 MB/s eta 0:00:00
     -------------------------------------- 126.5/126.5 kB 1.5 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 1.7 MB/s eta 0:00:00
     ---------------------------------------- 1.7/1.7 MB 1.3 MB/s eta 0:00:00
     ---------------------------------------- 5.6/5.6 MB 2.6 MB/s eta 0:00:00
     ---------------------------------------- 57.5/57.5 kB 1.5 MB/s eta 0:00:00
     ---------------------------------------- 4.3/4.3 MB 2.6 MB/s eta 0:00:00
     -------------------------------------- 65.5/65.5 kB 442.0 kB/s eta 0:00:00
     -------------------------------------- 181.8/181.8 kB 1.8 MB/s eta 0:00:00
     -------------------------------------- 151.

### Dataset Loading

In [ ]:
# Load Dataset
from google.colab import drive
drive.mount('/content/drive')

In [28]:
# Load Dataset
file = open("C:\\Users\\Prathamesh\\Downloads\\1661-0.txt", "r", encoding = "utf8")

time: 0 ns (started: 2023-08-20 12:15:43 +05:30)


### Data Preproseccing 

In [29]:
# store file in list
lines = []
for i in file:
    lines.append(i)
    
# Convert list to string
data = ""
for i in lines:
  data = ' '. join(lines) 
 
#replace unnecessary stuff with space
data = data.replace('\n', '').replace('\r', '').replace('\ufeff', '').replace('“','').replace('”','')  #new line, carriage return, unicode character --> replace by space
 
#remove unnecessary spaces 
data = data.split()
data = ' '.join(data)


time: 14 s (started: 2023-08-20 12:15:45 +05:30)


In [30]:
# check
data[:500]

"Project Gutenberg's The Adventures of Sherlock Holmes, by Arthur Conan Doyle This eBook is for the use of anyone anywhere at no cost and with almost no restrictions whatsoever. You may copy it, give it away or re-use it under the terms of the Project Gutenberg License included with this eBook or online at www.gutenberg.net Title: The Adventures of Sherlock Holmes Author: Arthur Conan Doyle Release Date: November 29, 2002 [EBook #1661] Last Updated: May 20, 2019 Language: English Character set en"

time: 0 ns (started: 2023-08-20 12:16:35 +05:30)


#### Lower Casing

In [31]:
data = data.lower()

time: 15 ms (started: 2023-08-20 12:16:38 +05:30)


In [32]:
data[:500]

"project gutenberg's the adventures of sherlock holmes, by arthur conan doyle this ebook is for the use of anyone anywhere at no cost and with almost no restrictions whatsoever. you may copy it, give it away or re-use it under the terms of the project gutenberg license included with this ebook or online at www.gutenberg.net title: the adventures of sherlock holmes author: arthur conan doyle release date: november 29, 2002 [ebook #1661] last updated: may 20, 2019 language: english character set en"

time: 0 ns (started: 2023-08-20 12:16:41 +05:30)


#### Removing Punctuations

In [33]:
# removing punctuations
import string
translator = str.maketrans('', '', string.punctuation)
data = data.translate(translator)

time: 62 ms (started: 2023-08-20 12:16:49 +05:30)


In [34]:
# check for update
data[:500]

'project gutenbergs the adventures of sherlock holmes by arthur conan doyle this ebook is for the use of anyone anywhere at no cost and with almost no restrictions whatsoever you may copy it give it away or reuse it under the terms of the project gutenberg license included with this ebook or online at wwwgutenbergnet title the adventures of sherlock holmes author arthur conan doyle release date november 29 2002 ebook 1661 last updated may 20 2019 language english character set encoding utf8  star'

time: 0 ns (started: 2023-08-20 12:16:51 +05:30)


### Tokenization

In [ ]:
# Tokenization
# Downloading needed libraries
nltk.download('punkt')

# Tokenization
cluster_df['cluster_data'] = cluster_df['cluster_data'].apply(nltk.word_tokenize)

# Checking the observation after manipulation
cluster_df['cluster_data'][0]

In [35]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])

time: 141 ms (started: 2023-08-20 12:22:03 +05:30)


In [36]:
# saving the tokenizer for predict function
pickle.dump(tokenizer, open('token.pkl', 'wb'))

time: 16 ms (started: 2023-08-20 12:22:13 +05:30)


In [37]:
sequence_data = tokenizer.texts_to_sequences([data])[0]
sequence_data[:15]

[136, 4694, 1, 957, 4, 122, 33, 45, 536, 2112, 2113, 27, 958, 14, 22]

time: 125 ms (started: 2023-08-20 12:23:54 +05:30)


In [38]:
len(sequence_data)

107583

time: 16 ms (started: 2023-08-20 12:24:07 +05:30)


In [39]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'i': 3,
 'of': 4,
 'to': 5,
 'a': 6,
 'in': 7,
 'that': 8,
 'it': 9,
 'you': 10,
 'he': 11,
 'was': 12,
 'his': 13,
 'is': 14,
 'my': 15,
 'have': 16,
 'with': 17,
 'as': 18,
 'had': 19,
 'at': 20,
 'which': 21,
 'for': 22,
 'not': 23,
 'but': 24,
 'be': 25,
 'me': 26,
 'this': 27,
 'we': 28,
 'from': 29,
 'there': 30,
 'said': 31,
 'upon': 32,
 'holmes': 33,
 'so': 34,
 'him': 35,
 'her': 36,
 'she': 37,
 'your': 38,
 'all': 39,
 'very': 40,
 'been': 41,
 'on': 42,
 'no': 43,
 'what': 44,
 'by': 45,
 'one': 46,
 'are': 47,
 'then': 48,
 'were': 49,
 'an': 50,
 'would': 51,
 'when': 52,
 'out': 53,
 'up': 54,
 'do': 55,
 'could': 56,
 'has': 57,
 'man': 58,
 'if': 59,
 'into': 60,
 'or': 61,
 'who': 62,
 'mr': 63,
 'little': 64,
 'will': 65,
 'some': 66,
 'see': 67,
 'down': 68,
 'now': 69,
 'our': 70,
 'may': 71,
 'should': 72,
 'they': 73,
 'us': 74,
 'am': 75,
 'over': 76,
 'can': 77,
 'more': 78,
 'about': 79,
 'think': 80,
 'well': 81,
 'must': 82,
 'shall':

time: 63 ms (started: 2023-08-20 12:24:48 +05:30)


In [40]:
vocab_size = len(tokenizer.word_index) + 1
print(vocab_size)

9178
time: 0 ns (started: 2023-08-20 12:27:15 +05:30)


In [41]:
sequences = []
 
for i in range(3, len(sequence_data)):
    words = sequence_data[i-3:i+1]
    sequences.append(words)

time: 282 ms (started: 2023-08-20 12:29:22 +05:30)


In [42]:
print("The Length of sequences are: ", len(sequences))

The Length of sequences are:  107580
time: 0 ns (started: 2023-08-20 12:29:53 +05:30)


In [43]:
sequences = np.array(sequences)
sequences[:10]

array([[ 136, 4694,    1,  957],
       [4694,    1,  957,    4],
       [   1,  957,    4,  122],
       [ 957,    4,  122,   33],
       [   4,  122,   33,   45],
       [ 122,   33,   45,  536],
       [  33,   45,  536, 2112],
       [  45,  536, 2112, 2113],
       [ 536, 2112, 2113,   27],
       [2112, 2113,   27,  958]])

time: 94 ms (started: 2023-08-20 12:30:21 +05:30)


In [44]:
X = []
y = []

for i in sequences:
    X.append(i[0:3])
    y.append(i[3])

time: 109 ms (started: 2023-08-20 12:30:58 +05:30)


In [45]:
X = np.array(X)
y = np.array(y)
print("Data: ", X[:10])
print("Response: ", y[:10])

Data:  [[ 136 4694    1]
 [4694    1  957]
 [   1  957    4]
 [ 957    4  122]
 [   4  122   33]
 [ 122   33   45]
 [  33   45  536]
 [  45  536 2112]
 [ 536 2112 2113]
 [2112 2113   27]]
Response:  [ 957    4  122   33   45  536 2112 2113   27  958]
time: 78 ms (started: 2023-08-20 12:31:21 +05:30)


In [47]:
X.shape

(107580, 3)

time: 0 ns (started: 2023-08-20 12:35:43 +05:30)


In [46]:
y = to_categorical(y, num_classes=vocab_size)
y[:5]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

time: 203 ms (started: 2023-08-20 12:31:45 +05:30)


In [48]:
y.shape

(107580, 9178)

time: 0 ns (started: 2023-08-20 12:35:56 +05:30)


## Creating the model

In [49]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=3))
model.add(LSTM(1000, return_sequences=True))
model.add(LSTM(1000))
model.add(Dense(1000, activation="relu"))
model.add(Dense(vocab_size, activation="softmax"))


time: 4.92 s (started: 2023-08-20 12:37:31 +05:30)


In [50]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 10)             91780     
                                                                 
 lstm (LSTM)                 (None, 3, 1000)           4044000   
                                                                 
 lstm_1 (LSTM)               (None, 1000)              8004000   
                                                                 
 dense (Dense)               (None, 1000)              1001000   
                                                                 
 dense_1 (Dense)             (None, 9178)              9187178   
                                                                 
Total params: 22327958 (85.17 MB)
Trainable params: 22327958 (85.17 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
time: 15 ms (s

## Model Training

In [56]:
from tensorflow.keras.callbacks import ModelCheckpoint
 
checkpoint = ModelCheckpoint("next_words.h5", monitor='loss', verbose=1, save_best_only=True)
model.compile(loss="categorical_crossentropy", optimizer=Adam(learning_rate=0.001))
model.fit(X, y, epochs=10, batch_size=50, callbacks=[checkpoint])

Epoch 1/10
2152/2152 [==============================] - ETA: 0s - loss: 5.1946
Epoch 1: loss improved from inf to 5.19463, saving model to next_words.h5
2152/2152 [==============================] - 1002s 463ms/step - loss: 5.1946
Epoch 2/10
2152/2152 [==============================] - ETA: 0s - loss: 4.9519
Epoch 2: loss improved from 5.19463 to 4.95193, saving model to next_words.h5
2152/2152 [==============================] - 904s 420ms/step - loss: 4.9519
Epoch 3/10
2152/2152 [==============================] - ETA: 0s - loss: 4.7505
Epoch 3: loss improved from 4.95193 to 4.75046, saving model to next_words.h5
2152/2152 [==============================] - 951s 442ms/step - loss: 4.7505
Epoch 4/10
2152/2152 [==============================] - ETA: 0s - loss: 4.5579
Epoch 4: loss improved from 4.75046 to 4.55795, saving model to next_words.h5
2152/2152 [==============================] - 986s 458ms/step - loss: 4.5579
Epoch 5/10
2152/2152 [==============================] - ETA: 0s - loss:

time: 2h 40min 34s (started: 2023-08-20 16:09:57 +05:30)


In [ ]:
# Load the model and tokenizer
from tensorflow.keras.models import load_model

model = load_model('next_words.h5')
tokenizer = pickle.load(open('token.pkl', 'rb'))
 
def Predict_Next_Words(model, tokenizer, text):
 
  sequence = tokenizer.texts_to_sequences([text])
  sequence = np.array(sequence)
  preds = np.argmax(model.predict(sequence))
  predicted_word = ""
   
  for key, value in tokenizer.word_index.items():
      if value == preds:
          predicted_word = key
          break
   
  print(predicted_word)
  return predicted_word
while(True):
  text = input("Enter your line: ")
   
  if text == "0":
      print("Execution completed.....")
      break
   
  else:
      try:
          text = text.split(" ")
          text = text[-3:]
          print(text)
         
          Predict_Next_Words(model, tokenizer, text)
           
      except Exception as e:
        print("Error occurred: ",e)
        continue

Enter your line: Produced by an anonymous Project
['an', 'anonymous', 'Project']
1/1 [==============================] - 1s 1s/step
gutenberg
Enter your line: The Adventures of
['The', 'Adventures', 'of']
1/1 [==============================] - 0s 45ms/step
sherlock
Enter your line: I had seen little of Holmes
['little', 'of', 'Holmes']
1/1 [==============================] - 0s 48ms/step
lysander
Enter your line: The Project Gutenberg eBook of
['Gutenberg', 'eBook', 'of']
1/1 [==============================] - 0s 53ms/step
the
Enter your line: how can you abuse your own
['abuse', 'your', 'own']
1/1 [==============================] - 0s 54ms/step
art
Enter your line: He could not help seeing that you were about five times as
['five', 'times', 'as']
1/1 [==============================] - 0s 50ms/step
to
Enter your line: and her sister
['and', 'her', 'sister']
1/1 [==============================] - 0s 48ms/step
was
Enter your line: and her sister was
['her', 'sister', 'was']
1/1 [==========

## Conclusion -

From the above results it is seen that we are correctly predicting the next word by evaluating previous three words.
We found almost 90% of time we got correct result as per out dataset.

# Thanks !